# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=10, unique=True, verbose_name=b'Codigo IBGE:')),
                ('nome', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, verbose_name=b'Bairro:')),
            ],
        ),
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[(b'C', b'CELULAR'), (b'F', b'COMERCIAL'), (b'R', b'RESIDENCIAL'), (b'O', b'OUTROS')], default=b'C', error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=1, verbose_name=b'Tipo:')),
                ('numero', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=20, verbose_name=b'Numero:')),
                ('nome_contato', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=50, verbose_name=b'Nome do Contato:')),
                ('cargo_setor', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=50, null=True, verbose_name=b'Cargo ou Setor:')),
                ('email', models.EmailField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=18, unique=True, verbose_name=b'Cpf / Cnpj:')),
                ('nome_razao', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, verbose_name=b'Nome / Raz\xc3\xa3o Social:')),
                ('apelido_fantasia', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=50, null=True, verbose_name=b'Apelido / Nome Fantasia:')),
                ('registro_geral', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=12, null=True, verbose_name=b'Identidade:')),
                ('tipo_registro', models.CharField(default=b'C', error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=1, null=True, verbose_name=b'Tipo Registro:')),
                ('inscricao_estadual', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=10, null=True, verbose_name=b'Inscri\xc3\xa7\xc3\xa3o Estadual:')),
                ('inscricao_municipal', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=10, null=True, verbose_name=b'Inscri\xc3\xa7\xc3\xa3o Municipal:')),
                ('inscricao_rural', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=10, null=True, verbose_name=b'Inscri\xc3\xa7\xc3\xa3o Rural:')),
                ('nascimento_fundacao', models.DateField(blank=True, null=True, verbose_name=b'Nascimento / Funda\xc3\xa7\xc3\xa3o:')),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numeracao_protocolo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=2, unique=True, verbose_name=b'Codigo IBGE:')),
                ('sigla', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=2, unique=True, verbose_name=b'Sigla:')),
                ('nome', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, unique=True, verbose_name=b'Estado:')),
                ('regiao', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=20, verbose_name=b'Regi\xc3\xa3o:')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=5, null=True, verbose_name=b'Numero:')),
                ('complemento', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, null=True, verbose_name=b'Complemento:')),
            ],
        ),
        migrations.CreateModel(
            name='localizacao_simples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=8, unique=True, verbose_name=b'Codigo Postal:')),
                ('logradouro', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, null=True, verbose_name=b'Logradouro:')),
                ('numero', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=5, null=True, verbose_name=b'Numero:')),
                ('complemento', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, null=True, verbose_name=b'Complemento:')),
                ('bairro', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, verbose_name=b'Bairro:')),
                ('codigo_ibge', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=7, unique=True, verbose_name=b'Codigo Municipal:')),
                ('municipio', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, verbose_name=b'Municipio:')),
                ('estado', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, unique=True, verbose_name=b'Estado:')),
                ('pais', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=30, unique=True, verbose_name=b'Pa\xc3\xads:')),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=8, unique=True, verbose_name=b'Codigo Postal:')),
                ('nome', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, verbose_name=b'Endere\xc3\xa7o:')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=7, unique=True, verbose_name=b'Codigo Municipal:')),
                ('nome', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, verbose_name=b'Municipio:')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='natureza_juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_natureza', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=5, unique=True, verbose_name=b'C\xc3\xb3digo:')),
                ('natureza_juridica', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, unique=True, verbose_name=b'Natureza Jur\xc3\xaddica:')),
            ],
        ),
        migrations.CreateModel(
            name='observacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True, verbose_name=b'Data:')),
                ('descricao', models.TextField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=500, verbose_name=b'Descri\xc3\xa7\xc3\xa3o: ')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, unique=True, verbose_name=b'Pa\xc3\xads:')),
                ('sigla', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=2, unique=True, verbose_name=b'Sigla:')),
            ],
            options={
                'verbose_name': 'Pa\xeds',
                'verbose_name_plural': 'Pa\xedses',
            },
        ),
        migrations.AddField(
            model_name='localizacao',
            name='logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.Logradouro'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.Pais'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='endereco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entidade.localizacao_simples'),
        ),
        migrations.AddField(
            model_name='contato',
            name='entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.entidade'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.Municipio'),
        ),
        migrations.AlterUniqueTogether(
            name='bairro',
            unique_together=set([('nome', 'municipio')]),
        ),
    ]
