# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao_simples',
            name='estado',
            field=models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=100, verbose_name=b'Estado:'),
        ),
        migrations.AlterField(
            model_name='localizacao_simples',
            name='pais',
            field=models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=30, verbose_name=b'Pa\xc3\xads:'),
        ),
    ]
