# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
