# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0002_auto_20160512_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao_simples',
            name='codigo_ibge',
            field=models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Campo Obrigat\xc3\xb3rio!'}, max_length=7, verbose_name=b'Codigo Municipal:'),
        ),
    ]
