# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='tipo_contrato',
            new_name='cliente',
        ),
    ]
