# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0005_contrato_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
