# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidade', '0002_auto_20160512_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'Item:')),
                ('referencia', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'M\xc3\xaas de Refer\xc3\xaancia:')),
                ('vencimento', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'Vencimento:')),
                ('valor', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'Valor:')),
                ('complemento', models.TextField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=500, null=True, verbose_name=b'Complemento:')),
            ],
        ),
        migrations.CreateModel(
            name='protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(auto_now=True)),
                ('numeracao_destinatario', models.IntegerField(null=True)),
                ('data_recebimento', models.DateField(null=True)),
                ('recebido_por', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, null=True, verbose_name=b'Recebido por:')),
                ('doc_receptor', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=20, null=True, verbose_name=b'Identidade:')),
                ('situacao', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidade_destinataria', to='entidade.entidade')),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidade_emissora', to='entidade.entidade')),
            ],
        ),
        migrations.AddField(
            model_name='item_protocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.protocolo'),
        ),
    ]
