# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidade', '0003_auto_20170206_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, null=True, verbose_name=b'Nome:')),
                ('descricao', models.TextField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=500, null=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o:')),
            ],
        ),
        migrations.CreateModel(
            name='item_protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'Item:')),
                ('referencia', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'M\xc3\xaas de Refer\xc3\xaancia:')),
                ('vencimento', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'Vencimento:')),
                ('valor', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, verbose_name=b'Valor:')),
                ('complemento', models.TextField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=500, null=True, verbose_name=b'Complemento:')),
            ],
        ),
        migrations.CreateModel(
            name='protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitido_por', models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, null=True, verbose_name=b'Emitido por:')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('hora_emissao', models.TimeField(auto_now_add=True)),
                ('numeracao_destinatario', models.CharField(max_length=5, null=True)),
                ('nome_avulso', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_avulso', models.CharField(blank=True, max_length=500, null=True)),
                ('documento_avulso', models.CharField(blank=True, max_length=30, null=True)),
                ('contatos_avulso', models.CharField(blank=True, max_length=50, null=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('hora_recebimento', models.TimeField(blank=True, null=True)),
                ('recebido_por', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=100, null=True, verbose_name=b'Recebido por:')),
                ('doc_receptor', models.CharField(blank=True, error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=20, null=True, verbose_name=b'Identidade:')),
                ('situacao', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidade_destinatario', to='entidade.entidade')),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidade_emissora', to='entidade.entidade')),
            ],
        ),
        migrations.AddField(
            model_name='item_protocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.protocolo'),
        ),
    ]
