# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolo',
            old_name='nome_destinatario',
            new_name='nome_avulso',
        ),
        migrations.AddField(
            model_name='protocolo',
            name='contatos_avulso',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='documento_avulso',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='endereco_avulso',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidade_destinatario', to='entidade.entidade'),
        ),
    ]
