# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 07:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preferencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salariominimo',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 16, 7, 48, 47, 467000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salariominimo',
            name='inicio_vigencia',
            field=models.DateField(default='2017-01-01', verbose_name='In\xedcio da vig\xeancia:'),
        ),
        migrations.AlterField(
            model_name='salariominimo',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 16, 7, 48, 59, 89000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
