# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
