# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0003_auto_20170206_0152'),
        ('servico', '0003_auto_20170317_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cadastrado_por', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_plano_cadastrado_por', to='entidade.entidade')),
                ('plano', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='servico.Plano')),
                ('servico', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='servico.Servico')),
            ],
        ),
    ]
