# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_itemplano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplano',
            name='servico',
            field=models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=500, null=True, verbose_name='Servi\xe7os:'),
        ),
    ]
