# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_auto_20170323_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemplano',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='itemplano',
            name='plano',
        ),
        migrations.AddField(
            model_name='plano',
            name='servicos',
            field=models.CharField(error_messages={b'invalid': b'Formato Inv\xc3\xa1lido!', b'required': b'Precisa ser Informado!'}, max_length=500, null=True, verbose_name='Servi\xe7os:'),
        ),
        migrations.DeleteModel(
            name='ItemPlano',
        ),
    ]
